BEGIN TRANSACTION;
INSERT INTO "Asistencias" ("id","usuario","evento_id") VALUES (7,'admin',11);
INSERT INTO "Asistencias" ("id","usuario","evento_id") VALUES (11,'natsi9',14);
INSERT INTO "Asistencias" ("id","usuario","evento_id") VALUES (12,'natsi9',12);
INSERT INTO "Asistencias" ("id","usuario","evento_id") VALUES (14,'test9',14);
INSERT INTO "Eventos" ("id","nombre","descripcion","fecha","hora","lugar","precio","estadoAnimo","tematica","creador") VALUES (3,'Nat','test','2025-04-08','01:40','CDMX',778.0,'Enojado',NULL,NULL);
INSERT INTO "Eventos" ("id","nombre","descripcion","fecha","hora","lugar","precio","estadoAnimo","tematica","creador") VALUES (10,'test','1','2025-04-30','04:17','cd',1111.0,'Relajado',NULL,NULL);
INSERT INTO "Eventos" ("id","nombre","descripcion","fecha","hora","lugar","precio","estadoAnimo","tematica","creador") VALUES (11,'Test','test2','2025-05-10','07:06','madrid',45555.0,'Aburrido',NULL,NULL);
INSERT INTO "Eventos" ("id","nombre","descripcion","fecha","hora","lugar","precio","estadoAnimo","tematica","creador") VALUES (12,'test','123','2025-05-13','20:00','Madrid',23444.0,'Ansioso',NULL,'natsi9');
INSERT INTO "Eventos" ("id","nombre","descripcion","fecha","hora","lugar","precio","estadoAnimo","tematica","creador") VALUES (14,'test99','hello','2025-05-16','04:04','mexico',223.0,'Enojado',NULL,NULL);
INSERT INTO "SugerenciasFeedbacks" ("id","tipo","texto") VALUES (2,'feedback','test');
INSERT INTO "SugerenciasFeedbacks" ("id","tipo","texto") VALUES (4,'feedback','me gusta la primera imagen');
INSERT INTO "TestResults" ("id","username","fecha","mood") VALUES (1,'natsi9','2025-05-07 12:25:57','FELIZ');
INSERT INTO "TestResults" ("id","username","fecha","mood") VALUES (2,'natsi9','2025-05-07 12:27:00','TRISTE');
INSERT INTO "TestResults" ("id","username","fecha","mood") VALUES (3,'natsi9','2025-05-07 12:29:39','FELIZ');
INSERT INTO "TestResults" ("id","username","fecha","mood") VALUES (4,'test9','2025-05-07 19:09:31','TRISTE');
INSERT INTO "TestResults" ("id","username","fecha","mood") VALUES (5,'test9','2025-05-07 19:11:08','RELAJADO');
INSERT INTO "TestResults" ("id","username","fecha","mood") VALUES (6,'test9','2025-05-07 19:12:48','TRISTE');
INSERT INTO "TestResults" ("id","username","fecha","mood") VALUES (7,'test9','2025-05-07 19:13:14','ENOJADO');
INSERT INTO "TestResults" ("id","username","fecha","mood") VALUES (8,'test9','2025-05-07 19:38:52','FELIZ');
INSERT INTO "usuarios" ("id","nombre","apellido","edad","email","username","password","role") VALUES (1,'Nat','Cas',22,'test@cas.es','Lun','$2b$10$ijUgjGKgVbbxCfpkIPU3kO48VhUes8AsGwITlgpWhh8uF43dRDq4m','user');
INSERT INTO "usuarios" ("id","nombre","apellido","edad","email","username","password","role") VALUES (2,'Nat','Cas',22,'test@test.com','nats','$2b$10$1bABL7jAooq9kbD6lTx5Ju7K55bFrw4XjXtqEx5uYXSxDJoAtMq/2','user');
INSERT INTO "usuarios" ("id","nombre","apellido","edad","email","username","password","role") VALUES (3,'Nat','Cas',5,'lunsa@gmail.com','n','$2b$10$1s7YQGCJO5wIHyYBYmeiuedTlYfltXG0Ctk44n1OEoE.xvWbFyCL6','user');
INSERT INTO "usuarios" ("id","nombre","apellido","edad","email","username","password","role") VALUES (4,'Nat','Cas',34,'test@gmail.com','nati','$2b$10$89XpGM4Wji3wGf80uQTLFOTKkwri4L61rYa4telSD.wo1Y2I2erqS','user');
INSERT INTO "usuarios" ("id","nombre","apellido","edad","email","username","password","role") VALUES (5,'Test','Cas',1,'lunsa9@gmail.com','lun9','$2b$10$UUokKw1an.hd6qlC3F5m3.BE8sWwrLNO5703cFQ8knBSFDYuCU0jq','user');
INSERT INTO "usuarios" ("id","nombre","apellido","edad","email","username","password","role") VALUES (9,'Admin','Moodvent',30,'admin@moodvent.com','admin','$2b$10$Sw4hKUpDgaa.JYb/FpGFQeTIebAxa0dchLs30ztPYuK8vSTO7vawO','admin');
INSERT INTO "usuarios" ("id","nombre","apellido","edad","email","username","password","role") VALUES (10,'Nat','Cas',19,'nat02@gmail.com','natsi9','$2b$10$mFRpeOzV2PgqfEHFBDtiE.fqPjyW66lGjk6Vxk4oaHcgZyBFNM5D2','user');
INSERT INTO "usuarios" ("id","nombre","apellido","edad","email","username","password","role") VALUES (11,'Nat','Cad',12,'testi9@gmail.com','Lunsa999','$2b$10$i6xgUGapzrxL0MUNH1eOBe.4SNwux3WG44QNmhw8NmlQBdV4eqhgy','user');
INSERT INTO "usuarios" ("id","nombre","apellido","edad","email","username","password","role") VALUES (12,'Test2','cas',23,'test1@tes3t.com','test9','$2b$10$PzjsHiJiCRUi0FCmrwgxFekTsmw1YEqJcuBtjb82k8KNLRr7QYsD2','user');
COMMIT;
